version: '3.8'

services:
  web:
    build: docker
    volumes:
      - .:/var/www/html
      - ./docker/boost_config_local.php:/var/www/html/common/code/boost_config_local.php
      - /opt/www/shared:/opt/www/shared
    ports:
      - "8080:80"
