  <div>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post"
    target="_top" style=
    "width: 250px; margin-left:auto; margin-right: auto;">
      <input type="hidden" name="cmd" value="_s-xclick" /> <input type=
      "hidden" name="hosted_button_id" value="B8N63QM4ZDN74" /> <input type=
      "image" src=
      "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border=
      "0" name="submit" alt="PayPal The safer, easier way to pay online!"
      style="display:block; margin-left:auto; margin-right:auto;" />

      <p><button type="submit" style=
      "width:250px; height:64px; white-space:normal;">Donate once-off, or a
      recurring donation with Paypal or Credit/Debit card</button></p>
    </form>
  </div>
